[package]
name = "winbloat"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["TamKungZ_ <dev@tamkungz.me>"]
description = "Fast and memory-efficient disk analyzer for Windows"
default-run = "winbloat"
homepage = "https://github.com/TamKungZ/WinBloat"
repository = "https://github.com/TamKungZ/WinBloat"
readme = "README.md"
keywords = ["disk-usage", "windows", "filesystem", "analyzer"]
categories = ["command-line-utilities", "filesystem"]

[[bin]]
name = "winbloat"
path = "src/main.rs"

[[bin]]
name = "winbloat-gui"
path = "src/gui_main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
eframe = {
    version = "0.36",
    default-features = false,
    features = ["default_fonts", "glow", "x11", "wayland"],
}
image = { version = "0.25", default-features = false, features = ["ico"] }
jwalk = "0.9"
owo-colors = { version = "4", features = ["supports-colors"] }
ratatui = "0.30"

[target.'cfg(windows)'.dependencies]
rfd = { version = "0.15", default-features = false, features = ["common-controls-v6"] }

[build-dependencies]
winres = "0.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true