[package]
name = "winbloat"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["TamKungZ_ <dev@tamkungz.me>"]
description = "Fast and memory-efficient disk analyzer for Windows"

[[bin]]
name = "winbloat"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
eframe = {
    version = "0.33",
    default-features = false,
    features = ["default_fonts", "glow", "x11", "wayland"],
}
jwalk = "0.9"
owo-colors = { version = "4", features = ["supports-colors"] }
ratatui = "0.30"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true